/*
 * MOP.java
 *
 * Created on 08 January 2009, 12:42
 */

package com.tolk.asim.gui;

import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;

/**
 *
 * @author  James
 */
public class MainOptionPanel extends javax.swing.JPanel implements ActionListener, ChangeListener {

    private MainFrame gui;
    
    /** Creates new form MOP */
    public MainOptionPanel(MainFrame gui, Dimension size) {
        this.gui = gui;
        setMinimumSize(size);
        setSize(size);
        initComponents();
        setListeners(); 
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    private void setListeners() {
        playButton.addActionListener(this);
        speedSlider.addChangeListener(this);
        zoomSlider.addChangeListener(this);
        drawnCheck.addActionListener(this);
        plantGrowthSlider.addChangeListener(this);
        plantDistCheck.addActionListener(this);
        plantConstantCheck.addActionListener(this);
        mutationDegreeSlider.addChangeListener(this);
        mutationRateSlider.addChangeListener(this);
    }

    public void actionPerformed(ActionEvent e) {
        sendSettings();
    }

    public void stateChanged(ChangeEvent e) {
        sendSettings();
    }

    public void sendSettings() {
        boolean play = playButton.isSelected();
        int speed = speedSlider.getValue();
        double zoom = (double) zoomSlider.getValue() / 100;
        boolean drawn = drawnCheck.isSelected();
        int plantGrowth = plantGrowthSlider.getValue();
        boolean plantDistributed = plantDistCheck.isSelected();
        boolean plantConstant = plantConstantCheck.isSelected();
        int mutationDegree = mutationDegreeSlider.getValue();
        int mutationRate = mutationRateSlider.getValue();

        gui.setSimulationSettings(play, speed, zoom, drawn, plantGrowth, plantDistributed, plantConstant, mutationRate, mutationDegree);
    }
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        plantDistCheck = new javax.swing.JCheckBox();
        playButton = new javax.swing.JToggleButton();
        drawnCheck = new javax.swing.JCheckBox();
        speedSlider = new javax.swing.JSlider();
        plantGrowthSlider = new javax.swing.JSlider();
        zoomSlider = new javax.swing.JSlider();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        mutationRateSlider = new javax.swing.JSlider();
        jLabel11 = new javax.swing.JLabel();
        mutationDegreeSlider = new javax.swing.JSlider();
        jLabel12 = new javax.swing.JLabel();
        plantConstantCheck = new javax.swing.JCheckBox();

        setPreferredSize(new Dimension(310, 600));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel1.setText("Program Properties");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel5.setText("Vegetation Properties");

        jLabel6.setText("Growth Rate");

        jLabel2.setText("Speed");

        jLabel3.setText("Zoom");

        jLabel4.setText("Drawn");

        jLabel8.setText("Play/Pause");

        jLabel7.setText("Distribute");

        plantDistCheck.setName("plantDistCheck"); // NOI18N

        playButton.setSelected(true);
        playButton.setText("Pause");
        playButton.setName("playButton"); // NOI18N

        drawnCheck.setSelected(true);
        drawnCheck.setName("drawnCheck"); // NOI18N

        speedSlider.setMajorTickSpacing(10);
        speedSlider.setMinimum(1);
        speedSlider.setPaintLabels(true);
        speedSlider.setPaintTicks(true);
        speedSlider.setValue(1);
        speedSlider.setMaximumSize(new Dimension(200, 45));
        speedSlider.setMinimumSize(new Dimension(200, 45));
        speedSlider.setName("speedSlider"); // NOI18N

        plantGrowthSlider.setMajorTickSpacing(50);
        plantGrowthSlider.setMaximum(400);
        plantGrowthSlider.setPaintLabels(true);
        plantGrowthSlider.setPaintTicks(true);
        plantGrowthSlider.setMaximumSize(new Dimension(200, 45));
        plantGrowthSlider.setMinimumSize(new Dimension(200, 45));
        plantGrowthSlider.setName("plantGrowthSlider"); // NOI18N

        zoomSlider.setMajorTickSpacing(10);
        zoomSlider.setMinimum(10);
        zoomSlider.setPaintLabels(true);
        zoomSlider.setPaintTicks(true);
        zoomSlider.setValue(100);
        zoomSlider.setMaximumSize(new Dimension(200, 45));
        zoomSlider.setMinimumSize(new Dimension(200, 45));
        zoomSlider.setName("sizeSlider"); // NOI18N

        jSeparator1.setMinimumSize(new Dimension(310, 10));
        jSeparator1.setPreferredSize(new Dimension(310, 10));

        jSeparator2.setMinimumSize(new Dimension(310, 10));
        jSeparator2.setPreferredSize(new Dimension(310, 10));

        jSeparator3.setMinimumSize(new Dimension(310, 10));
        jSeparator3.setPreferredSize(new Dimension(310, 10));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel9.setText("Mutation Properties");

        jLabel10.setText("Mutation Rate");

        mutationRateSlider.setMajorTickSpacing(10);
        mutationRateSlider.setPaintLabels(true);
        mutationRateSlider.setPaintTicks(true);
        mutationRateSlider.setValue(10);
        mutationRateSlider.setMaximumSize(new Dimension(200, 45));
        mutationRateSlider.setMinimumSize(new Dimension(200, 45));
        mutationRateSlider.setName("mutationRateSlider"); // NOI18N

        jLabel11.setText("Mutation Degree");

        mutationDegreeSlider.setMajorTickSpacing(10);
        mutationDegreeSlider.setPaintLabels(true);
        mutationDegreeSlider.setPaintTicks(true);
        mutationDegreeSlider.setValue(10);
        mutationDegreeSlider.setMaximumSize(new Dimension(200, 45));
        mutationDegreeSlider.setMinimumSize(new Dimension(200, 45));
        mutationDegreeSlider.setName("mutationDegreeSlider"); // NOI18N

        jLabel12.setText("Constant");

        plantConstantCheck.setSelected(true);
        plantConstantCheck.setName("plantDistCheck"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6)
                    .addComponent(jLabel12)
                    .addComponent(jLabel4))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(playButton)
                    .addComponent(plantDistCheck)
                    .addComponent(speedSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(plantGrowthSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(plantConstantCheck)
                    .addComponent(zoomSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(drawnCheck))
                .addGap(11, 11, 11))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel9))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(mutationRateSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mutationDegreeSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jSeparator3, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jLabel1)
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(playButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(speedSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(zoomSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(drawnCheck)
                    .addComponent(jLabel4))
                .addGap(27, 27, 27)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(plantGrowthSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(plantDistCheck))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(plantConstantCheck))
                .addGap(25, 25, 25)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(mutationRateSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mutationDegreeSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox drawnCheck;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSlider mutationDegreeSlider;
    private javax.swing.JSlider mutationRateSlider;
    private javax.swing.JCheckBox plantConstantCheck;
    private javax.swing.JCheckBox plantDistCheck;
    private javax.swing.JSlider plantGrowthSlider;
    private javax.swing.JToggleButton playButton;
    private javax.swing.JSlider speedSlider;
    private javax.swing.JSlider zoomSlider;
    // End of variables declaration//GEN-END:variables

}
